### ISSUE TITLE
Get " RuntimeError: CUDA error (3): initialization error " when running train.py with GPU

### ISSUE THREAD

**Issue by TennisRobot2016** [filipradenovic/cnnimageretrieval-pytorch#21]
Traceback (most recent call last):
  File "/home/superuser/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/superuser/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/superuser/Projects/cnnimageretrieval-pytorch-master-20181101/cirtorch/examples/train.py", line 558, in <module>
    main()
  File "/home/superuser/Projects/cnnimageretrieval-pytorch-master-20181101/cirtorch/examples/train.py", line 268, in main
    loss = train(train_loader, model, criterion, optimizer, epoch)
  File "/home/superuser/Projects/cnnimageretrieval-pytorch-master-20181101/cirtorch/examples/train.py", line 307, in train
    for i, (input, target) in enumerate(train_loader):
  File "/home/superuser/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/superuser/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/superuser/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/superuser/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/superuser/Projects/cnnimageretrieval-pytorch-master-20181101/cirtorch/datasets/traindataset.py", line 110, in __getitem__
    output.append(self.loader(self.images[self.nidxs[index][i]]))
RuntimeError: CUDA error (3): initialization error

It has no error when uses CPU only.
I am using Python 3.6 , PyTorch 0.4.1 , and CUDA 9.2, what's wrong?

**Comment by TennisRobot2016** [comment]
I solved the problem with setting --workers = 0 in parameters.

**Comment by filipradenovic** [comment]
Hm, this is the first time something like this happens. The code was tested with PyTorch 0.3.0, so the version might be the issue. We will look into it.

Thank you for reporting it!
